In [1]:
import numpy as np
from sklearn.ensemble import IsolationForest
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split 

In [3]:
data = pd.read_csv("../Data/maize_labeled.csv")
X = data[["nitrogen","phosphorus","potassium","ph","bulk_density","cation_exchange"]]
y= data["YA"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=20,shuffle=True)


In [4]:
y

0      0.250219
1      0.171145
2      1.980000
3      1.050000
4      1.920000
         ...   
103    0.660000
104    4.242857
105    3.285714
106    2.160000
107    4.242857
Name: YA, Length: 108, dtype: float64

### One-class Svm

In [74]:
from sklearn.svm import OneClassSVM
import numpy as np
from sklearn.metrics import accuracy_score

# Assuming X_train is your training data for the single class
clf = OneClassSVM(gamma='scale', nu=0.008).fit(X_train)

scores_test = clf.predict(X_test)
accuracy = accuracy_score(scores_test,[1 for _ in range(len(scores_test))])
accuracy
-8.9327370
33.5833040

0.8636363636363636

In [79]:
value= clf.predict([[0.8,7.2,48.4,5.6,1.5,5.7]])
value

/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but OneClassSVM was fitted with feature names
  warnings.warn(


array([-1])

In [82]:
value= clf.predict([[1.8,6.4,329.3,5.9,1.03,15.4]])
value

/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but OneClassSVM was fitted with feature names
  warnings.warn(


array([-1])

In [ ]:
value= clf.predict([[1.8,6.4,329.3,5.9,0.99,15.4]])
value

In [67]:
from sklearn.preprocessing import MinMaxScaler


scores_train = clf.decis([[20,7.2,48.4,5.6,1.5,5.7]])
print(scores_train)
# Normalize scores to get probabilities
scaler = MinMaxScaler()
scores_train_scaled = scaler.fit_transform(scores_train.reshape(-1, 1))
print("Training Data Anomaly Probabilities:", scores_train_scaled)


AttributeError: 'OneClassSVM' object has no attribute 'decis'

In [8]:


# Example data (training set)

# Create and fit the Isolation Forest model
knn = NearestNeighbors(n_neighbors=3)
knn.fit(X_train)




NearestNeighbors(n_neighbors=3)

In [10]:
# Example new data
distances, _ = knn.kneighbors(X_train)
avg_distances = np.mean(distances, axis=1)

# Set a threshold as the mean + standard deviation of the average distances
threshold = np.mean(avg_distances) + np.std(avg_distances)
print("Threshold:", threshold)

# Function to determine if a point is an anomaly
def is_anomaly(point, threshold):
    distances, _ = knn.kneighbors([point])
    avg_distance = np.mean(distances)
    return avg_distance > threshold

# Example new data
X_test = np.array([[0.4, 7,100,6.5,1.3,8], [10,4,5,6,7, 10]])

# Predict anomalies in new data
test_anomalies = [is_anomaly(point, threshold) for point in X_test]
print("Test Data Anomalies:", test_anomalies)

Threshold: 10.90720187488661
Test Data Anomalies: [True, True]


/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


In [16]:


# Predict anomalies in new data
test_anomalies = [is_anomaly(point, threshold) for point in X_train.to_numpy()]
print("Test Data Anomalies:", test_anomalies)

Test Data Anomalies: [False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]


/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/home

In [40]:
from sklearn.svm import OneClassSVM
import numpy as np


# Assuming X_train is your training data for the single class
clf = OneClassSVM(gamma='scale', nu=0.008).fit(X_train)

# Predict on new data


In [24]:
predictions = clf.predict(X_train)

In [38]:
# Calculate decision function scores for the training data
from sklearn.preprocessing import MinMaxScaler


scores_train = clf.decision_function([X_train.to_numpy()[1]])
print(scores_train)
# Normalize scores to get probabilities
scaler = MinMaxScaler()
scores_train_scaled = scaler.fit_transform(scores_train.reshape(-1, 1))
print("Training Data Anomaly Probabilities:", scores_train_scaled)


[0.01342729]
Training Data Anomaly Probabilities: [[0.]]


/home/godson/devtools/anaconda3/lib/python3.9/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but OneClassSVM was fitted with feature names
  warnings.warn(


In [5]:
from sklearn.linear_model import LinearRegression

model  = LinearRegression()

In [7]:
model.fit(X_train,y_train)

LinearRegression()

In [8]:
predictions = model.predict(X_test)

In [9]:
predictions

array([2.3510854 , 1.67846048, 1.77207249, 1.12538368, 1.38258046,
       1.87913213, 2.05003042, 1.69382618, 2.24929253, 2.08470112,
       2.13984107, 1.53372341, 2.2797673 , 1.75631693, 2.49853979,
       2.09391762, 1.36660348, 2.70958164, 1.93884442, 2.3607898 ,
       2.491259  , 1.48075377])

In [10]:
from sklearn.metrics import mean_absolute_error

In [12]:
mean_absolute_error(y_test,predictions)



0.6240702235472068

In [52]:
import numpy as np
from sklearn.ensemble import IsolationForest,RandomForestClassifier
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [44]:
data = pd.read_csv("../Data/all_crops_labeled_cleaned.csv")

In [45]:
data.head()

STATIONNAME  LONGITUDE  LATITUDE  ELEVATION_METER   COUNTRY   CROP  \
0        Adet     37.480     11.27           2240.0  Ethiopia  wheat   
1        Ambo     37.835      8.96           2100.0  Ethiopia  wheat   
2       Ayira     35.330      9.06           1700.0  Ethiopia  wheat   
3    Butajira     38.220      8.08           1840.0  Ethiopia  wheat   
4  Debre Zeit     39.000      8.72           1900.0  Ethiopia  wheat   

         YA        YW     YW-YA        YP  ...  YP_CV_TEMPORAL  \
0  2.264167  9.535426  7.271260  9.960867  ...             NaN   
1  2.432833  8.645642  6.212808  9.691156  ...             NaN   
2  1.841167  8.019422  6.178255  8.019306  ...             NaN   
3  2.517667  9.013532  6.495865  9.091533  ...             NaN   
4  2.661667  8.501563  5.839896  9.086763  ...             NaN   

   YA_CV_TEMPORAL  CLIMATEZONE  AREA_IN_CLIMATEZONE_HA  nitrogen  phosphorus  \
0        0.185680         6701                   33930       1.3       243.7   
1        0.155960         5501                   34690       1.4       297.9   
2        0.364394         7701                    4331       2.0       220.4   
3        0.146454         5701                   20238       2.3       163.0   
4        0.194539         6301                   39285       1.3       269.4   

   potassium   ph  bulk_density  cation_exchange  
0        7.2  6.0          1.19             21.2  
1       13.9  6.4          1.15             35.6  
2        7.2  5.4          1.09             23.5  
3       10.0  5.7          1.09             17.2  
4       13.9  6.7          1.23             26.1  

[5 rows x 25 columns]

In [46]:
data.columns

Index(['STATIONNAME', 'LONGITUDE', 'LATITUDE', 'ELEVATION_METER', 'COUNTRY',
       'CROP', 'YA', 'YW', 'YW-YA', 'YP', 'YP-YA', 'WPP', 'WPA',
       'CROPPING_INTENSITY', 'YW_CV_TEMPORAL', 'YP_CV_TEMPORAL',
       'YA_CV_TEMPORAL', 'CLIMATEZONE', 'AREA_IN_CLIMATEZONE_HA', 'nitrogen',
       'phosphorus', 'potassium', 'ph', 'bulk_density', 'cation_exchange'],
      dtype='object')

In [47]:
y = data["CROP"]
X= data[['nitrogen',
       'phosphorus', 'potassium', 'ph', 'bulk_density', 'cation_exchange']]

In [48]:
scaler = StandardScaler()
array_scaled = scaler.fit_transform(X)
X = pd.DataFrame(array_scaled,columns=X.columns)

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify=y)

In [53]:
model = LogisticRegression()

In [54]:
model.fit(X_train,y_train)

LogisticRegression()

In [55]:
predictions = model.predict(X_test)

In [56]:
predictions

array(['maize', 'maize', 'maize', 'maize', 'millet', 'maize', 'maize',
       'maize', 'sorghum', 'sorghum', 'maize', 'maize', 'rice', 'sorghum',
       'maize', 'maize', 'maize', 'millet', 'maize', 'millet', 'maize',
       'maize', 'maize', 'maize', 'millet', 'wheat', 'maize', 'maize',
       'millet', 'maize', 'millet', 'millet', 'maize', 'maize', 'wheat',
       'maize', 'maize', 'millet', 'millet', 'maize', 'maize', 'sorghum',
       'sorghum', 'maize', 'maize', 'maize', 'millet', 'maize', 'millet',
       'maize', 'sorghum', 'maize', 'millet', 'maize', 'maize', 'maize',
       'maize', 'sorghum', 'sorghum', 'maize', 'millet', 'maize',
       'sorghum', 'rice', 'maize', 'millet', 'maize', 'maize', 'maize',
       'maize'], dtype=object)

In [57]:
y_test

227      maize
180      maize
197      maize
263      maize
234      maize
        ...   
103    sorghum
201      maize
205      maize
68     sorghum
3        wheat
Name: CROP, Length: 70, dtype: object

In [58]:
accuracy_score(y_test,predictions)

0.3142857142857143

In [31]:
import catboost as cb
model = cb.CatBoostClassifier(verbose=0)

<frozen importlib._bootstrap>:228: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 232 from PyObject


In [32]:
model.fit(X_train,y_train)

In [39]:
predictions = model.predict(X_test)
accuracy_score(y_test,predictions)

0.15714285714285714

In [40]:
predictions

array([['sorghum'],
       ['maize'],
       ['rice'],
       ['maize'],
       ['sorghum'],
       ['millet'],
       ['sorghum'],
       ['maize'],
       ['maize'],
       ['maize'],
       ['millet'],
       ['sorghum'],
       ['millet'],
       ['millet'],
       ['maize'],
       ['sorghum'],
       ['millet'],
       ['millet'],
       ['maize'],
       ['wheat'],
       ['sorghum'],
       ['millet'],
       ['sorghum'],
       ['maize'],
       ['sorghum'],
       ['maize'],
       ['maize'],
       ['rice'],
       ['sorghum'],
       ['sorghum'],
       ['wheat'],
       ['millet'],
       ['sorghum'],
       ['maize'],
       ['millet'],
       ['maize'],
       ['sorghum'],
       ['millet'],
       ['millet'],
       ['maize'],
       ['maize'],
       ['millet'],
       ['rice'],
       ['rice'],
       ['maize'],
       ['maize'],
       ['maize'],
       ['millet'],
       ['sugarcane'],
       ['millet'],
       ['wheat'],
       ['millet'],
       ['maize'],
       

In [34]:
predictions = model.predict_proba(X_test)

In [37]:
model.classes_

array(['maize', 'millet', 'rice', 'sorghum', 'sugarcane', 'wheat'],
      dtype=object)

In [35]:
predictions

array([[3.04952369e-01, 5.39546505e-02, 3.15344443e-01, 3.25089879e-01,
        2.70592029e-04, 3.88066947e-04],
       [8.96982800e-01, 1.21585065e-02, 4.47462583e-03, 4.26654964e-02,
        5.53209657e-04, 4.31653615e-02],
       [3.26750635e-01, 5.50972528e-02, 4.80056041e-01, 1.36720808e-01,
        6.31798888e-04, 7.43464571e-04],
       [6.18536145e-01, 1.21516462e-01, 5.30878795e-02, 1.73802810e-01,
        7.88737097e-03, 2.51693327e-02],
       [1.16288837e-01, 2.19660449e-02, 1.02434472e-02, 8.37014599e-01,
        3.65431296e-03, 1.08327592e-02],
       [4.07388420e-01, 4.56124204e-01, 1.28051765e-03, 3.59971650e-02,
        6.32060274e-04, 9.85776330e-02],
       [7.09236662e-02, 3.23208418e-01, 7.97182295e-02, 5.18347526e-01,
        2.97711556e-03, 4.82504429e-03],
       [8.67174314e-01, 2.87282288e-02, 6.21439520e-02, 4.14842881e-02,
        2.20844054e-04, 2.48373018e-04],
       [2.92577142e-01, 1.15587490e-01, 1.30890043e-01, 2.25225379e-01,
        1.43904156e-03, 

In [38]:
y_test

275     millet
58     sorghum
119       rice
255      maize
248      maize
        ...   
333     millet
110    sorghum
252      maize
206      maize
37     sorghum
Name: CROP, Length: 70, dtype: object

In [41]:
from sklearn.model_selection import cross_val_score


scores = cross_val_score(model, X, y, cv=5)

In [42]:
scores

array([0.25714286, 0.21428571, 0.12857143, 0.2       , 0.27536232])